package com.mybatis.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordertime
     *
     * @mbg.generated
     */
    private Date ordertime;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbg.generated
     */
    private BigDecimal total;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uid
     *
     * @mbg.generated
     */
    private Integer uid;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertime
     *
     * @return the value of order.ordertime
     * @mbg.generated
     */
    public Date getOrdertime() {
        return ordertime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertime
     *
     * @param ordertime the value for order.ordertime
     * @mbg.generated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uid
     *
     * @return the value of order.uid
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uid
     *
     * @param uid the value for order.uid
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    
    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", ordertime=" + ordertime +
                ", total=" + total +
                ", uid=" + uid +
                '}';
    }
}